---
features:
  - |
    Robot Amikoo? Hi There! My name is Amikoo! I am controlled over the
    network via MQ Telemetry Transport. In the future I might be the one in
    charge of giving tours to our Visitors with little human intervention!
  - |
    Coji Application? Amikoo can now speak.
