FROM xe1gyq/openvino

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ARG OPENVINO_INSTALL=/opt/intel/openvino

ENV TIMEZONE America/Mexico_City
USER root
ENV HOME_USER /home/user

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl-dev && \
    rm -rf /var/lib/apt/lists/*

ADD --chown=1000:1000 main.sh /home/user/
RUN /bin/bash -c 'chmod +x /home/user/main.sh'

RUN chown -R user /home/user
USER user

WORKDIR /opt/intel/openvino/deployment_tools/tools/model_downloader
RUN sudo ./downloader.py --name pedestrian-and-vehicle-detector-adas-0001 --output_dir $HOME_USER && \
    sudo ./downloader.py --name pedestrian-and-vehicle-detector-adas-0001-fp16 --output_dir $HOME_USER

WORKDIR /home/user

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh && \
    git clone https://github.com/intel-iot-devkit/parking-lot-counter-cpp.git && \
    mkdir parking-lot-counter-cpp/build/ && \
    ls parking-lot-counter-cpp/build/ && \
    cd parking-lot-counter-cpp/build && \
    cmake .. && \
    make"

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh"
RUN echo "source $OPENVINO_INSTALL/bin/setupvars.sh" >> /home/user/.bashrc

ARG DEVICE
ENV DEVICE="${DEVICE}"

ARG VIDEO
ENV VIDEO="${VIDEO}"

ARG ENTRANCE
ENV ENTRANCE=${ENTRANCE}

ENTRYPOINT ["/home/user/main.sh"]
CMD ["/home/user/main.sh", "${DEVICE}", ${VIDEO}, ${ENTRANCE}]
