FROM xe1gyq/openvino

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ARG OPENVINO_INSTALL=/opt/intel/openvino

ENV TIMEZONE America/Mexico_City
USER root
ENV HOME_USER /home/user
ENV OPENVINO_R1_2019 26237c87b2b8c2da6dbcd62610e6298f2723cafa

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl-dev && \
    rm -rf /var/lib/apt/lists/*

ADD --chown=1000:1000 main.sh /home/user/
RUN /bin/bash -c 'chmod +x /home/user/main.sh'

RUN chown -R user /home/user
USER user

WORKDIR /opt/intel/openvino/deployment_tools/tools/model_downloader
RUN sudo ./downloader.py --name pedestrian-detection-adas-0002 --output_dir $HOME_USER

WORKDIR /home/user

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh && \
    git clone https://github.com/intel-iot-devkit/restricted-zone-notifier-cpp.git && \
    mkdir restricted-zone-notifier-cpp/build/ && \
    cd restricted-zone-notifier-cpp/ && \
    git reset --hard $OPENVINO_R1_2019 && \
    cd build/ && \
    cmake .. && \
    make"

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh"
RUN echo "source $OPENVINO_INSTALL/bin/setupvars.sh" >> /home/user/.bashrc

ARG DEVICE
ENV DEVICE="${DEVICE}"

ENTRYPOINT ["/home/user/main.sh"]
CMD ["/home/user/main.sh", "${DEVICE}"]
