homeassistant:
  # Name of the location where Home Assistant is running
  name: Hochob

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_altitude

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Mexico_City

  # Load packages
  packages: !include_dir_named components/packages
