FROM  homeassistant/home-assistant

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ENV TIMEZONE America/Mexico_City
USER root

RUN apk update && \
    apk --no-cache add \    
    alsa-utils \
    alsaconf \
    alsa-utils-doc \
    eog \
    mesa-dri-intel \
    mesa-gl \
    mosquitto-clients \
    mplayer \
    openrc \
    psmisc \
    pulseaudio \ 
    python2 \
    shadow \
    vim \
    vlc 

ADD asoundrc /root/.asoundrc

