FROM  homeassistant/home-assistant

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ENV TIMEZONE America/Mexico_City
USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    eog \
    psmisc \
    mosquitto-clients && \
    rm -rf /var/lib/apt/lists/*
