FROM xe1gyq/openvino

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ARG OPENVINO_INSTALL=/opt/intel/openvino

ENV TIMEZONE America/Mexico_City
USER root
ENV HOME_USER /home/user
ENV OPENVINO_R1_2019 047f337955d6e0b065a2ce0c4514ad8151c5a829

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl-dev \
    git && \
    rm -rf /var/lib/apt/lists/*

ADD --chown=1000:1000 main.sh /home/user/
RUN /bin/bash -c 'chmod +x /home/user/main.sh'

RUN chown -R user /home/user
USER user

WORKDIR /opt/intel/openvino/deployment_tools/tools/model_downloader
RUN sudo ./downloader.py --name face-detection-adas-0001 --output_dir $HOME_USER && \
    sudo ./downloader.py --name head-pose-estimation-adas-0001 --output_dir $HOME_USER

WORKDIR /home/user

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh && \
    git clone https://github.com/intel-iot-devkit/shopper-gaze-monitor-cpp.git && \
    mkdir shopper-gaze-monitor-cpp/build/ && \
    cd shopper-gaze-monitor-cpp && \
    git reset --hard $OPENVINO_R1_2019 && \
    cd build/ && \
    cmake .. && \
    make"

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh"
RUN echo "source $OPENVINO_INSTALL/bin/setupvars.sh" >> /home/user/.bashrc

ARG DEVICE
ENV DEVICE="${DEVICE}"

ARG TARGET
ENV TARGET="${TARGET}"

ENTRYPOINT ["/home/user/main.sh"]
CMD ["/home/user/main.sh", "${DEVICE}", "${TARGET}"]
